---
title: "Experience"
---

My research interests are broadly in causal inference, data integration, and parametric and non-parametric modeling. I am interested in substantive questions in mental health, education, substance use, and aging.

## Professional Experience

-   **Research Assistant,** *Dr. Elizabeth Stuart at Johns Hopkins Bloomberg School of Public Health, Baltimore, Maryland,* Spring 2019 -- present

-   **Data Science Intern,** *Mathematica Policy Research, Washington, DC,* Summer 2023

-   **Graduate Trainee,** *Epidemiology and Biostatistics of Aging Training Grant at Johns Hopkins Bloomberg School of Public Health, Baltimore, Maryland,* Fall 2020 -- Spring 2023

-   **CIPhER Intern in Education Research and Assessment,** *Center for Innovative Pharmacy Education and Research (CIPhER) at UNC Eshelman School of Pharmacy, Chapel Hill, North Carolina,* Summer 2019

-   **Course Assistant,** *Center for Leadership Education at Johns Hopkins University, Baltimore, Maryland,* Fall 2018 -- Spring 2020

-   **Student/Researcher**, *Summer Institute in Biostatistics (SIBS) at North Carolina State University, Raleigh, North Carolina,* Summer 2018

## Leadership Experience

-   **Co-President,** *Biostatistics Student Organization, Johns Hopkins University,* 2022 -- present

-   **Biostatistics Department Representative,** *Mental Health Graduate Network, Johns Hopkins University,* 2021 -- present

-   **Mentoring Committee and Curriculum Committee Member,** *Biostatistics Student Organization, Johns Hopkins University,* 2020 -- present

-   **Council of Emerging and New Statisticians (CENS) Member,** *ENAR of International Biometrics Society,* 2023 - present

-   **Team Captain,** *Varsity Women's Soccer, Johns Hopkins University,* 2019

-   **Assistant New Member Director,** *Phi Mu Gamma Tau Chapter, Johns Hopkins University,* 2019

-   **Captains Cohort Member,** *Blue Jays LEAD, Johns Hopkins University,* Spring 2019 -- 2020
